services:
  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'
  api1:
    build: ./
    hostname: api1
    ports:
      - '81:1100'
    restart: on-failure
    volumes:
      - ${PWD}/settings:/destiny-ghost-api/settings
      - ${PWD}/databases:/destiny-ghost-api/databases
  api2:
    build: ./
    hostname: api2
    ports:
      - '82:1100'
    restart: on-failure
    volumes:
      - ${PWD}/settings:/destiny-ghost-api/settings
      - ${PWD}/databases:/destiny-ghost-api/databases
  nginx:
    build: ./nginx
    ports:
    - '80:80'
    depends_on:
    - api1
    - api2
  wiremock:
      image: wiremock/wiremock
      ports:
        - "8080:8080"
      volumes:
        - ./mocks/wiremock:/home/wiremock/mappings
  cosmosdb:
    image: mcr.microsoft.com/cosmosdb/linux/azure-cosmos-emulator
    tty: true
    environment:
      - AZURE_COSMOS_EMULATOR_ENABLE_DATA_PERSISTENCE=true
    ports:
      - 8081:8081
